### ISSUE TITLE
Unit of morb and Morb

### ISSUE THREAD

**Issue by yilinzhao222** [wannier-berri/wannier-berri#300] opened 2023-12-21 17:38 UTC
Hi Stepan,

Sorry to bother you with the unit issue again. I noticed that the unit of Morb (wberri.calculators.static.Morb) is '\mu_B'. Is the unit of morb (wberri.calculators.tabulate.OrbitalMoment) '\mu_B' or SI unit 'A*m^2'? 

In addition, I get kind of confused when calculating morb with w90 system and pythTB systems. Could you give me a clue about the formula used to calculate the morb (wberri.calculators.tabulate.OrbitalMoment) please? Is there any difference for the formula of morb between these two kinds of systems?

Best regards,
Yilin

**Comment by stepan-tsirkin** [comment] 2023-12-22 15:01
duplicate of #301

**Closed by stepan-tsirkin** 2023-12-22 15:01 UTC
Labels: duplicate
