### ISSUE TITLE
Unexpected error in interpolating bands in wannier berri

### ISSUE THREAD

**Issue by subhadipniser333** [wannier-berri/wannier-berri#208] opened 2022-08-11 08:30 UTC
Hi wannier-berri developers,
I am trying to do the tutorial "interpolating bands, Berry curvatures, and integrating them" as directed by you for my input files for a material. I am facing a few problems. Firstly in 6 the step, i.e., in "# plot the bands and compare with QuantumEspresso," I have tried to plot the bands from vasp output. When I am trying to change the energy limit, i.e., Emin and Emax from -2 to 2, it is showing "UnboundLocalError: local variable '_line' referenced before assignment," but when I am trying with '-5' to '5' range it is showing proper band structure. Secondly, the wannier bands' energy windows are in negative how do I get the energy window of my choice? Also, the wannier band is not matching with vasp bands. In the berry curvature plot, the energy window for the bands is very small and negative. How to change this energy range?
Thank you very much.

**Comment by stepan-tsirkin** [comment] 2022-09-19 13:51
duplicate of #207

**Closed** 2022-09-19 13:50 UTC
Labels: duplicate
