### ISSUE TITLE
Incorrect SHC result calculated on ferromangetic Fe (bcc) using spn file gererated from Vasp

### ISSUE THREAD

**Issue by ngohainc** [wannier-berri/wannier-berri#277] opened 2023-09-20 11:28 UTC
Dear Developers,

I examine the anomalous spin hall effect (ASHE) on Fe (bcc) ferromagnet by using both VASP and QE methods. In the case of QE, the obtained result is quite consistent with the one reported on [PRB 99, 220405(R) (2019)] and [PRB 102, 144440 (2020)]. That is , SHC(1) ≈ 100 S/cm when m is aligned in the z direction while SHC (2) ≈ 520 S/cm as m is aligned in the x (or y) direction.  However, in the case of Vasp, the results are much different; SHC(1) ≈0 while  SHC (2) ≈ 80 S/cm. I used both VASP2WAN90 by ChengCheng-Xiao and vaspspn.py by Prof. Stepan to convert WAVECAR to spn file.  Nevertheless, these two methods exhibit the same incorrect result as mentioned above.
As I can see, the AHC calculations are consistent for both VASP and QE. Thus, I surmise that the problem is due to spn file.

Thanks Developers very much for creating those codes (especially vaspspn.py can generate spn file very fast) and I hope that this issue can be addressed. 

Best Regards,
NgoHai

**Comment by stepan-tsirkin** [comment] 2023-09-22 14:37
@ngohainc  

This seems like a duplicate of #274  . Please, post your message again there, and close the you opened here.

**Closed** 2023-09-23 01:27 UTC
Labels: duplicate
